### ISSUE TITLE
Very nice API

### ISSUE THREAD

**Issue by szepeviktor** [Arubacloud/pyArubaCloud#17]
Please consider developing a Salt Stack cloud driver
https://docs.saltstack.com/en/latest/topics/cloud/cloud.html
It is python.

**Comment by szepeviktor** [comment]
There is a VMware driver if it helps
https://github.com/saltstack/salt/tree/develop/salt/cloud/clouds

**Comment by blackms** [comment]
Hello, it seems to be based on libcloud, and we have it in roadmap.
