### ISSUE TITLE
Change OS

### ISSUE THREAD

**Issue by Melius-Group** [Arubacloud/pyArubaCloud#24]
How can I change OS on smart or pro vm via API? It can handle only admin pass change.

**Comment by blackms** [comment]
It's possible only on smart servers, I will work on it.

**Comment by Melius-Group** [comment]
How can I change OS on smart vm?

**Comment by blackms** [comment]
At the moment it's not possible to change the OS via json API, I will add the method as soon as it will be available on them.

**Comment by Melius-Group** [comment]
HI, may i ask what about change OS via API?

**Comment by Melius-Group** [comment]
Hi, Any update? :)

**Comment by blackms** [comment]
I think that this will take another 2 weeks. Please be patience :)

**Comment by Melius-Group** [comment]
Hi! What about with this issue? :) Thank You!

**Comment by blackms** [comment]
This enhancement is scheduled for September.

**Comment by blackms** [comment]
Implemented inside reinitialize_vm method for smart servers.
