### ISSUE TITLE
How can I change rDNS entry for VM's IPs?

### ISSUE THREAD

**Issue by Melius-Group** [Arubacloud/pyArubaCloud#28]
How can I change rDNS entry for VM's IPs via API?

**Comment by mikamakusa** [comment]
It's not implemented yet

**Comment by blackms** [comment]
Correct, this is not implemented yet. I will try to work on it next week.

**Comment by Melius-Group** [comment]
Thank You so much!

**Comment by Melius-Group** [comment]
HI, may I ask what about rDNS modif via API?

**Comment by Melius-Group** [comment]
Hi, any Update? :)

**Comment by blackms** [comment]
I'm working on it. Stay tuned :)

**Comment by blackms** [comment]
At the moment, the method is not exposed via our public API, we are working on it. Should be ready in about 2 weeks.

**Comment by Melius-Group** [comment]
Hi! Any update, for this issue?

**Comment by blackms** [comment]
This change is scheduled for September.

**Comment by Melius-Group** [comment]
Hi, There is an update for this issue?

**Comment by blackms** [comment]
Hi, checkout "NewStructure" branch, ReverseDns is already there.

**Comment by blackms** [comment]
Merged in master.

**Comment by Melius-Group** [comment]
Hi, 

Thank you so much, but I get the following error msg:
Traceback (most recent call last):
  File "rdns.py", line 1, in <module>
    from ArubaCloud.ReverseDns import ReverseDns
ImportError: No module named ReverseDns

How can I solve this?

Thank You

**Comment by Melius-Group** [comment]
I solv the error problem, but I get nothing as rdns.

The file:
import argparse

from ArubaCloud.ReverseDns import ReverseDns
from ArubaCloud.PyArubaAPI import CloudInterface

if __name__ == '__main__':
        parser = argparse.ArgumentParser()
        parser.add_argument('-d', '--datacenter', help='Specify datacenter to login.', action='store', dest='dc')
        parser.add_argument('-p', '--pattern', help='Specify pattern to search.', action='store', dest='pattern')
        parser.add_argument('-u', '--username', help='Specify username.', action='store', dest='username')
        parser.add_argument('-w', '--password', help='Specify password.', action='store', dest='password')
        parser.add_argument('--new-rdns', action='store', dest='new_rdns')
        p = parser.parse_args()

        ci = CloudInterface(dc=int(p.dc))
        rdns = ReverseDns(username=p.username, password=p.password, ws_uri=ci.wcf_baseurl)

        # get configured reverse dns
        print(rdns.get())

I use the correct DC and auth data, and the response is [ ].
rdns provisioned dc3 and dig command shows correctly.

Any idea?

**Comment by blackms** [comment]
Going to check it.

**Comment by blackms** [comment]
Solved, the Get method require the IP address to query:

```python
    def get(self, addresses):
        """
        :type addresses: list[str]
        :param addresses: (list[str]) List of addresses to retrieve their reverse dns
        Retrieve the current configured ReverseDns entries
        :return: (list) List containing the current ReverseDns Addresses
        """
        request = self._call(GetReverseDns, IPs=addresses)
        response = request.commit()
        return response['Value']
```

You need to specify the ip address and the method now will return the reverse addresses associated.

**Comment by Metzgher** [comment]
Hello, 

I've been getting the same error as Melious:

ImportError: No module named ReverseDns

Any tip on how to solve this?

**Comment by arubalucalasagni** [comment]
We are checking, Thanks a lot

**Comment by unigia** [comment]
Thank you for your report. We have fixed the problem and now it works:
``` python
    ci = CloudInterface(dc=int(p.dc))
    ci.login(username=p.username, password=p.password, load=True)
    ci.get_servers()

    rdns = ReverseDns.ReverseDns(username=p.username, password=p.password, ws_uri=ci.wcf_baseurl)

    # get configured reverse dns
    for vm in ci.vmlist:
	print(rdns.get(addresses=[vm.ip_addr]))
```
with both python version 2 and 3.
If you still have problems you can reopen the issue.
