### ISSUE TITLE
Can't get a list of scheduled tasks

### ISSUE THREAD

**Issue by andrexus** [Arubacloud/pyArubaCloud#36]
What should I pass to get_scheduled_operations method as start/end-Date in order to get a list of ScheduledTasks?

I get always the following response
`
{
	"ExceptionInfo": null,
	"ResultCode": 36,
	"ResultMessage": "SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM.\r\nExceptionCode=36\r\n",
	"Success": false,
	"Value": null
}
`

**Comment by aledesimone** [comment]
Dear Andrexux,
there's a bug on the json request format.

I made a bugfix and also added an example, you can preview it on commit
https://github.com/Arubacloud/pyArubaCloud/commit/db51f08d3a0f5e5083186c5f39353b196fdf27fd

The dates must be serialized as Microsoft JSON timestamp: "\/Date(1198908717056)\/".

Maybe tomorrow we'll update the master and also the pypi package, I will notify you of further updates.

Thank you!

**Comment by andrexus** [comment]
@aledesimone 
Thank you for fixing the bug. Is it already deployed on live? I'm asking because I don't have any errors now but also no results, even if status is "Success: true"
