### ISSUE TITLE
Bug during/after python3 installation + temp fix

### ISSUE THREAD

**Issue by endorxmr** [Arubacloud/pyArubaCloud#48]
When installing the library from github with `python3 setup.py install` I get the following error:

```
byte-compiling build/bdist.linux-x86_64/egg/ArubaCloud/__init__.py to __init__.cpython-35.pyc
  File "build/bdist.linux-x86_64/egg/ArubaCloud/__init__.py", line 1
    __version__ = 0.7.6
                      ^
SyntaxError: invalid syntax
```

This error also shows up when trying to run one of the examples:
```
Traceback (most recent call last):
  File "print_vm.py", line 3, in <module>
    from ArubaCloud.PyArubaAPI import CloudInterface
  File "/usr/local/lib/python3.5/dist-packages/ArubaCloud/__init__.py", line 1
    __version__ = 0.7.6
                      ^
SyntaxError: invalid syntax
```

A temporary fix is to simply open the `__init.py__` file in question and add quotes at the version number: `__version__ = "0.7.6"`
This seems to solve the issue.
I've briefly skimmed through the library, and found a similar error in multiple places.

**Comment by arubalucalasagni** [comment]
Thanks
