### ISSUE TITLE
holycraft

### ISSUE THREAD

**Issue by rhmkds** [Arubacloud/pyArubaCloud#56]
its not working anymore

**Comment by arubalucalasagni** [comment]
Hi @rhmkds, 
Can you send us some info about the error you are facing.

**Comment by rhmkds** [comment]
both python2.7 and python3 same result

```
Traceback (most recent call last):
  File "/root/pyArubaCloud/login.py", line 16, in <module>
    i.login(username=p.username, password=p.password, load=True)
  File "/root/pyArubaCloud/ArubaCloud/PyArubaAPI.py", line 66, in login
    self.get_ip()
  File "/root/pyArubaCloud/ArubaCloud/PyArubaAPI.py", line 334, in get_ip
    json_obj = self.call_method_post(method='GetPurchasedIpAddresses ', json_scheme=json_scheme)
  File "/root/pyArubaCloud/ArubaCloud/base/__init__.py", line 38, in call_method_post
    response = Http.post(url=url, data=json.dumps(json_scheme), headers=headers)
  File "/root/pyArubaCloud/ArubaCloud/helper/__init__.py", line 31, in post
    response = requests.post(url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by arubalucalasagni** [comment]
Could you send us the snippet of code that you are using, hiding your credentials?

I tried to create a Pro VM in python3 and it works:
```python
from ArubaCloud.PyArubaAPI import CloudInterface
from ArubaCloud.objects import ProVmCreator

ci = CloudInterface(dc=1)
ci.login(username="XXX-XXXX", password="XXXXXXXX", load=True)

ip = ci.purchase_ip()

c = ProVmCreator(name='debian01', admin_password='MyStrongPassword', template_id='2833', auth_obj=ci.auth)
c.set_cpu_qty(2)
c.set_ram_qty(6)
  
c.add_public_ip(public_ip_address_resource_id=ip.resid)
c.add_virtual_disk(20)
c.add_virtual_disk(40)

print(c.commit(url=ci.wcf_baseurl, debug=True))
```

**Comment by rhmkds** [comment]
I use this script to get list of my VPS
> https://github.com/Arubacloud/pyArubaCloud/blob/master/examples/print_vm.py

**Comment by arubalucalasagni** [comment]
can you make a `pip list` to show us your packages?

**Comment by rhmkds** [comment]
pip list
apt-xapian-index (0.45)
argparse (1.2.1)
chardet (2.0.1)
Cheetah (2.4.4)
cloud-init (0.7.5)
colorama (0.2.5)
configobj (4.7.2)
Cython (0.20.1post0)
fire (0.1.3)
gevent (1.0)
greenlet (0.4.2)
html5lib (0.999)
jsonpatch (1.3)
jsonpickle (1.0)
jsonpointer (1.0)
Landscape-Client (14.12)
lxml (3.3.3)
oauth (1.0.1)
PAM (0.4.2)
pip (1.5.4)
prettytable (0.7.2)
pyArubaCloud (0.7.11)
pycurl (7.19.3)
pyOpenSSL (0.13)
pyserial (2.6)
python-apt (0.9.3.5ubuntu2)
python-debian (0.1.21-nmu2ubuntu2)
PyYAML (3.10)
requests (2.2.1)
setuptools (3.3)
six (1.5.2)
ssh-import-id (3.21)
Twisted-Core (13.2.0)
Twisted-Names (13.2.0)
Twisted-Web (13.2.0)
UNKNOWN (0.0.0)
urllib3 (1.7.1)
wheel (0.24.0)
wsgiref (0.1.2)
zope.interface (4.0.5)

**Comment by arubalucalasagni** [comment]
Your problem depend on this package:
`requests (2.2.1)`
you could try to upgrade the package:

`pip install requests==2.20.1`

**Comment by rhmkds** [comment]
Still same error but I dont need it again, php is easier than py

**Comment by nanghele** [comment]
@rhmkds you could try 
`pip install --upgrade requests`

**Comment by rhmkds** [comment]
pip install --upgrade requests
```
Downloading/unpacking requests from https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl#sha256=65b3a120e4329e33c9889db89c80976c5272f56ea92d3e74da8a463992e3ff54
  Downloading requests-2.20.1-py2.py3-none-any.whl (57kB): 57kB downloaded
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Downloading/unpacking urllib3>=1.21.1,<1.25 (from requests)
  Downloading urllib3-1.24.1-py2.py3-none-any.whl (118kB): 118kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Requirement already up-to-date: idna>=2.5,<2.8 in /usr/local/lib/python2.7/dist-packages (from requests)
Installing collected packages: requests, urllib3, chardet
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: urllib3 1.7.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: chardet 2.0.1
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed requests urllib3 chardet
Cleaning up...
```

Still same error

**Comment by rhmkds** [comment]
> Traceback (most recent call last):
>   File "/root/pyArubaCloud/login.py", line 16, in <module>
>     i.login(username=p.username, password=p.password, load=True)
>   File "/root/pyArubaCloud/ArubaCloud/PyArubaAPI.py", line 66, in login
>     self.get_ip()
>   File "/root/pyArubaCloud/ArubaCloud/PyArubaAPI.py", line 334, in get_ip
>     json_obj = self.call_method_post(method='GetPurchasedIpAddresses ', json_scheme=json_scheme)
>   File "/root/pyArubaCloud/ArubaCloud/base/__init__.py", line 38, in call_method_post
>     response = Http.post(url=url, data=json.dumps(json_scheme), headers=headers)
>   File "/root/pyArubaCloud/ArubaCloud/helper/__init__.py", line 31, in post
>     response = requests.post(url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 88, in post
>     return request('post', url, data=data, **kwargs)
>   File "/usr/lib/python3/dist-packages/requests/api.py", line 44, in request
>     return session.request(method=method, url=url, **kwargs)
> TypeError: request() got an unexpected keyword argument 'json'

**Comment by arubalucalasagni** [comment]
Hi @rhmkds 
Could you copy here the result of  `pip list` to check the requests package version?

**Comment by rhmkds** [comment]
Oh yeah its request still 2.2.1 not upgraded, maybe i need remove its first

**Comment by arubalucalasagni** [comment]
what is your OS? 
Have you tried with `sudo -i pip install --upgrade requests`?

**Comment by rhmkds** [comment]
Old ubuntu 14.04
Cannot upgrade requests
It seem need ubuntu 16 or above to get it worked. 
:~# sudo -i pip install --upgrade requests
Downloading/unpacking requests from https://files.pythonhosted.org/packages/ff/17/5cbb026005115301a8fb2f9b0e3e8d32313142fe8b617070e7baad20554f/requests-2.20.1-py2.py3-none-any.whl#sha256=65b3a120e4329e33c9889db89c80976c5272f56ea92d3e74da8a463992e3ff54
  Downloading requests-2.20.1-py2.py3-none-any.whl (57kB): 57kB downloaded
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests)
Downloading/unpacking urllib3>=1.21.1,<1.25 (from requests)
  Downloading urllib3-1.24.1-py2.py3-none-any.whl (118kB): 118kB downloaded
Downloading/unpacking chardet>=3.0.2,<3.1.0 (from requests)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB): 133kB downloaded
Requirement already up-to-date: idna>=2.5,<2.8 in /usr/local/lib/python2.7/dist-packages (from requests)
Installing collected packages: requests, urllib3, chardet
  Found existing installation: requests 2.2.1
    Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: urllib3 1.7.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS  Found existing installation: chardet 2.0.1
    Not uninstalling chardet at /usr/lib/python2.7/dist-packages, owned by OSSuccessfully installed requests urllib3 chardet
Cleaning up...

**Comment by arubalucalasagni** [comment]
yes you have always the same error:
`Not uninstalling requests at /usr/lib/python2.7/dist-packages, owned by OS`

How it is write here https://askubuntu.com/questions/985626/unable-to-upgrade-requests-lib-python

You can try to uninstall your pip and install the latest one
uninstall
`sudo pip uninstall pip`
reinstall
`sudo apt install python-pip`
after this you can retry
sudo -i pip install --upgrade requests
