### ISSUE TITLE
Authentication failed, token not found

### ISSUE THREAD

**Issue by mlocati** [Arubacloud/pyArubaCloud#62]
I'm trying to use the print_reversedns module.

I launch it with these parameters:
`--datacenter=1` (which is the IT1 datacenter)
`--username=<my username>`
`--password=<my password>`

Where `<my username>` is the username I see in the [customer area](https://customerarea.aruba.it/#!/cloud/cloudDetails) page (it starts with `ARU-` followed by digits), and the password is the one I use to login to customerarea.aruba.it (for which I use the `...@aruba.it` username).

With those parameters, I have this exception:
```
RequestFailed
Request: {"ApplicationId": "GetPurchasedIpAddresses", "RequestId": "GetPurchasedIpAddresses", "SessionId": "GetPurchasedIpAddresses", "Password": "<my password>", "Username": "<my username>"}, Response: {'ExceptionInfo': None, 'ResultCode': 2, 'ResultMessage': 'Authentication failed, token not found.\r\nExceptionCode=2\r\n', 'Success': False}
  File "pyArubaCloud\ArubaCloud\base\__init__.py", line 43, in call_method_post
    raise RequestFailed("Request: {}, Response: {}".format(json_scheme, parsed_response))
  File "pyArubaCloud\ArubaCloud\PyArubaAPI.py", line 334, in get_ip
    json_obj = self.call_method_post(method='GetPurchasedIpAddresses ', json_scheme=json_scheme)
  File "pyArubaCloud\ArubaCloud\PyArubaAPI.py", line 66, in login
    self.get_ip()
  File "pyArubaCloud\examples\print_reversedns.py", line 15, in <module>
    ci.login(username=p.username, password=p.password, load=True)
```

Am I doing something wrong?

PS: I cloned this repository, I'm using master @ 5db264a611c78360d6a661e2dc41cdb6794ecea2

**Comment by marcobarzaghi** [comment]
The username is right, the password must be the one related with the ARU usename. In case you forgot it, you can reset it from the customer area (section Cloud).

**Comment by mlocati** [comment]
Great, thanks! I wasn't aware of that (IMHO the difference between the `...@aruba.it` account and the `ARU-...` account is not very clear in the documentation).
